version: '3.8'

services:
  decimal:
    image: ketan003/decimal-api:v1
    ports:
      - "5100:5100"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  devanagari:
    image: ketan003/devanagari-api:v1
    ports:
      - "5200:5200"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  unified:
    image: ketan003/unified-api:v1
    ports:
      - "5300:5300"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    configs:
      - source: nginx-default-conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  nginx-default-conf:
    external: true
